version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    networks:
      frontend:
        ipv4_address: 172.16.0.10
    restart: always

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  backend-wp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24